// <auto-generated />
using System;
using CulinaryAnalytics.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CulinaryAnalytics.Repositories.Migrations
{
    [DbContext(typeof(CaappContext))]
    [Migration("20240713021008_CaapContextInitialMigration")]
    partial class CaapContextInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.Common.DictionaryList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Deletor")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LookupCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Updator")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DictionaryLists", "Common");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(5499),
                            Deleted = false,
                            Description = "States",
                            ExternalId = "",
                            LookupCode = "STATES",
                            Name = "States"
                        },
                        new
                        {
                            Id = 2L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(5584),
                            Deleted = false,
                            Description = "Units of Measure",
                            ExternalId = "",
                            LookupCode = "UOM",
                            Name = "Units of Measure"
                        },
                        new
                        {
                            Id = 3L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(5587),
                            Deleted = false,
                            Description = "Ingredient Types",
                            ExternalId = "",
                            LookupCode = "INGREDIENTTYPES",
                            Name = "Ingredient Types"
                        });
                });

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.Common.DictionaryListItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Deletor")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("DictionaryListId")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LookupCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Updator")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryListId");

                    b.ToTable("DictionaryListItems", "Common");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9044),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "AL",
                            LookupCode = "AL",
                            Name = "Alabama"
                        },
                        new
                        {
                            Id = 2L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9061),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "AK",
                            LookupCode = "AK",
                            Name = "Alaska"
                        },
                        new
                        {
                            Id = 3L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9064),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "AZ",
                            LookupCode = "AZ",
                            Name = "Arizona"
                        },
                        new
                        {
                            Id = 4L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9066),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "AR",
                            LookupCode = "AR",
                            Name = "Arkansas"
                        },
                        new
                        {
                            Id = 5L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9068),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "CA",
                            LookupCode = "CA",
                            Name = "California"
                        },
                        new
                        {
                            Id = 6L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9097),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "CZ",
                            LookupCode = "CZ",
                            Name = "Canal Zone"
                        },
                        new
                        {
                            Id = 7L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9100),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "CO",
                            LookupCode = "CO",
                            Name = "Colorado"
                        },
                        new
                        {
                            Id = 8L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9102),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "CT",
                            LookupCode = "CT",
                            Name = "Connecticut"
                        },
                        new
                        {
                            Id = 9L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9104),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "DE",
                            LookupCode = "DE",
                            Name = "Delaware"
                        },
                        new
                        {
                            Id = 10L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9106),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "DC",
                            LookupCode = "DC",
                            Name = "District of Columbia"
                        },
                        new
                        {
                            Id = 11L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9108),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "FL",
                            LookupCode = "FL",
                            Name = "Florida"
                        },
                        new
                        {
                            Id = 12L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9110),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "GA",
                            LookupCode = "GA",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 13L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9112),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "GU",
                            LookupCode = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 14L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9114),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "HI",
                            LookupCode = "HI",
                            Name = "Hawaii"
                        },
                        new
                        {
                            Id = 15L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9116),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "ID",
                            LookupCode = "ID",
                            Name = "Idaho"
                        },
                        new
                        {
                            Id = 16L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9118),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "IL",
                            LookupCode = "IL",
                            Name = "Illinois"
                        },
                        new
                        {
                            Id = 17L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9119),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "IN",
                            LookupCode = "IN",
                            Name = "Indiana"
                        },
                        new
                        {
                            Id = 18L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9122),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "IA",
                            LookupCode = "IA",
                            Name = "Iowa"
                        },
                        new
                        {
                            Id = 19L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9124),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "KS",
                            LookupCode = "KS",
                            Name = "Kansas"
                        },
                        new
                        {
                            Id = 20L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9126),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "KY",
                            LookupCode = "KY",
                            Name = "Kentucky"
                        },
                        new
                        {
                            Id = 21L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9128),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "LA",
                            LookupCode = "LA",
                            Name = "Louisiana"
                        },
                        new
                        {
                            Id = 22L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9129),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "ME",
                            LookupCode = "ME",
                            Name = "Maine"
                        },
                        new
                        {
                            Id = 23L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9131),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "MD",
                            LookupCode = "MD",
                            Name = "Maryland"
                        },
                        new
                        {
                            Id = 24L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9133),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "MA",
                            LookupCode = "MA",
                            Name = "Massachusetts"
                        },
                        new
                        {
                            Id = 25L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9135),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "MI",
                            LookupCode = "MI",
                            Name = "Michigan"
                        },
                        new
                        {
                            Id = 26L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9137),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "MN",
                            LookupCode = "MN",
                            Name = "Minnesota"
                        },
                        new
                        {
                            Id = 27L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9139),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "MS",
                            LookupCode = "MS",
                            Name = "Mississippi"
                        },
                        new
                        {
                            Id = 28L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9141),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "MO",
                            LookupCode = "MO",
                            Name = "Missouri"
                        },
                        new
                        {
                            Id = 29L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9143),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "MT",
                            LookupCode = "MT",
                            Name = "Montana"
                        },
                        new
                        {
                            Id = 30L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9145),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "NE",
                            LookupCode = "NE",
                            Name = "Nebraska"
                        },
                        new
                        {
                            Id = 31L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9146),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "NV",
                            LookupCode = "NV",
                            Name = "Nevada"
                        },
                        new
                        {
                            Id = 32L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9148),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "NH",
                            LookupCode = "NH",
                            Name = "New Hampshire"
                        },
                        new
                        {
                            Id = 33L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9150),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "NJ",
                            LookupCode = "NJ",
                            Name = "New Jersey"
                        },
                        new
                        {
                            Id = 34L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9153),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "NM",
                            LookupCode = "NM",
                            Name = "New Mexico"
                        },
                        new
                        {
                            Id = 35L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9155),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "NY",
                            LookupCode = "NY",
                            Name = "New York"
                        },
                        new
                        {
                            Id = 36L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9156),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "NC",
                            LookupCode = "NC",
                            Name = "North Carolina"
                        },
                        new
                        {
                            Id = 37L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9158),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "ND",
                            LookupCode = "ND",
                            Name = "North Dakota"
                        },
                        new
                        {
                            Id = 38L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9160),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "OH",
                            LookupCode = "OH",
                            Name = "Ohio"
                        },
                        new
                        {
                            Id = 39L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9162),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "OK",
                            LookupCode = "OK",
                            Name = "Oklahoma"
                        },
                        new
                        {
                            Id = 40L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9164),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "OR",
                            LookupCode = "OR",
                            Name = "Oregon"
                        },
                        new
                        {
                            Id = 41L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9166),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "PA",
                            LookupCode = "PA",
                            Name = "Pennsylvania"
                        },
                        new
                        {
                            Id = 42L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9168),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "PR",
                            LookupCode = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 43L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9170),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "RI",
                            LookupCode = "RI",
                            Name = "Rhode Island"
                        },
                        new
                        {
                            Id = 44L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9171),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "SC",
                            LookupCode = "SC",
                            Name = "South Carolina"
                        },
                        new
                        {
                            Id = 45L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9173),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "SD",
                            LookupCode = "SD",
                            Name = "South Dakota"
                        },
                        new
                        {
                            Id = 46L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9175),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "TN",
                            LookupCode = "TN",
                            Name = "Tennessee"
                        },
                        new
                        {
                            Id = 47L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9177),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "TX",
                            LookupCode = "TX",
                            Name = "Texas"
                        },
                        new
                        {
                            Id = 48L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9179),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "UT",
                            LookupCode = "UT",
                            Name = "Utah"
                        },
                        new
                        {
                            Id = 49L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9180),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "VT",
                            LookupCode = "VT",
                            Name = "Vermont"
                        },
                        new
                        {
                            Id = 50L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9182),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "VI",
                            LookupCode = "VI",
                            Name = "Virgin Islands"
                        },
                        new
                        {
                            Id = 51L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9184),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "VA",
                            LookupCode = "VA",
                            Name = "Virginia"
                        },
                        new
                        {
                            Id = 52L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9186),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "WA",
                            LookupCode = "WA",
                            Name = "Washington"
                        },
                        new
                        {
                            Id = 53L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9188),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "WV",
                            LookupCode = "WV",
                            Name = "West Virginia"
                        },
                        new
                        {
                            Id = 54L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9190),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "WI",
                            LookupCode = "WI",
                            Name = "Wisconsin"
                        },
                        new
                        {
                            Id = 55L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9192),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "WY",
                            LookupCode = "WY",
                            Name = "Wyoming"
                        },
                        new
                        {
                            Id = 56L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9194),
                            Deleted = false,
                            Description = "Milligram",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "mg",
                            Name = "Milligram"
                        },
                        new
                        {
                            Id = 57L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9195),
                            Deleted = false,
                            Description = "Gram",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "g",
                            Name = "Gram"
                        },
                        new
                        {
                            Id = 58L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9197),
                            Deleted = false,
                            Description = "Kilogram",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "kg",
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 59L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9242),
                            Deleted = false,
                            Description = "Ounce",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "oz",
                            Name = "Ounce"
                        },
                        new
                        {
                            Id = 60L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9245),
                            Deleted = false,
                            Description = "Pound",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "lb",
                            Name = "Pound"
                        },
                        new
                        {
                            Id = 61L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9247),
                            Deleted = false,
                            Description = "Ton",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "ton",
                            Name = "Ton"
                        },
                        new
                        {
                            Id = 62L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9248),
                            Deleted = false,
                            Description = "Cup",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "cup",
                            Name = "Cup"
                        },
                        new
                        {
                            Id = 63L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9250),
                            Deleted = false,
                            Description = "Table Spoon",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "ts",
                            Name = "Table Spoon"
                        },
                        new
                        {
                            Id = 64L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9252),
                            Deleted = false,
                            Description = "Unit",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "unit",
                            Name = "Unit"
                        },
                        new
                        {
                            Id = 65L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9254),
                            Deleted = false,
                            Description = "Vegetable",
                            DictionaryListId = 3L,
                            ExternalId = "",
                            LookupCode = "VEG",
                            Name = "Vegetable"
                        },
                        new
                        {
                            Id = 66L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9256),
                            Deleted = false,
                            Description = "Meat",
                            DictionaryListId = 3L,
                            ExternalId = "",
                            LookupCode = "MEAT",
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 67L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9258),
                            Deleted = false,
                            Description = "Herb",
                            DictionaryListId = 3L,
                            ExternalId = "",
                            LookupCode = "HERB",
                            Name = "Herb"
                        },
                        new
                        {
                            Id = 68L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9260),
                            Deleted = false,
                            Description = "Fruit",
                            DictionaryListId = 3L,
                            ExternalId = "",
                            LookupCode = "FRUIT",
                            Name = "Fruit"
                        },
                        new
                        {
                            Id = 69L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9262),
                            Deleted = false,
                            Description = "Grain",
                            DictionaryListId = 3L,
                            ExternalId = "",
                            LookupCode = "GRAIN",
                            Name = "Grain"
                        },
                        new
                        {
                            Id = 70L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 12, 21, 10, 6, 892, DateTimeKind.Local).AddTicks(9264),
                            Deleted = false,
                            Description = "Spice",
                            DictionaryListId = 3L,
                            ExternalId = "",
                            LookupCode = "SPICE",
                            Name = "Spice"
                        });
                });

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.Common.DictionaryListItem", b =>
                {
                    b.HasOne("CulinaryAnalytics.Models.Entities.Common.DictionaryList", "Dictionary")
                        .WithMany("Items")
                        .HasForeignKey("DictionaryListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");
                });

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.Common.DictionaryList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
