// <auto-generated />
using System;
using CulinaryAnalytics.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CulinaryAnalytics.Repositories.Migrations
{
    [DbContext(typeof(CaappContext))]
    [Migration("20240713214108_AddingCommonSchema")]
    partial class AddingCommonSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.CRM.BusinessEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("AltPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("BusinessEntityTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Deletor")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LookupCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Updator")
                        .HasColumnType("int");

                    b.Property<string>("WebSite")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEntityTypeId");

                    b.ToTable("BusinessEntities", "CRM");
                });

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.CRM.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("AltPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("BusinessEntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Deletor")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("LookupCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Updator")
                        .HasColumnType("int");

                    b.Property<string>("WebSite")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEntityId");

                    b.ToTable("Locations", "CRM");
                });

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.CRM.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("AltPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Deletor")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Updator")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("People", "CRM");
                });

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.Common.DictionaryList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Deletor")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LookupCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Updator")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DictionaryLists", "Common");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(6572),
                            Deleted = false,
                            Description = "States",
                            ExternalId = "",
                            LookupCode = "STATES",
                            Name = "States"
                        },
                        new
                        {
                            Id = 2L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(6625),
                            Deleted = false,
                            Description = "Units of Measure",
                            ExternalId = "",
                            LookupCode = "UOM",
                            Name = "Units of Measure"
                        },
                        new
                        {
                            Id = 3L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(6628),
                            Deleted = false,
                            Description = "Ingredient Types",
                            ExternalId = "",
                            LookupCode = "INGREDIENTTYPES",
                            Name = "Ingredient Types"
                        },
                        new
                        {
                            Id = 4L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(6630),
                            Deleted = false,
                            Description = "Business Entity Types",
                            ExternalId = "",
                            LookupCode = "BUSINESSENTITYTYPES",
                            Name = "Business Entity Types"
                        });
                });

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.Common.DictionaryListItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Deletor")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("DictionaryListId")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LookupCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Updator")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryListId");

                    b.ToTable("DictionaryListItems", "Common");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9811),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "AL",
                            LookupCode = "AL",
                            Name = "Alabama"
                        },
                        new
                        {
                            Id = 2L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9831),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "AK",
                            LookupCode = "AK",
                            Name = "Alaska"
                        },
                        new
                        {
                            Id = 3L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9833),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "AZ",
                            LookupCode = "AZ",
                            Name = "Arizona"
                        },
                        new
                        {
                            Id = 4L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9835),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "AR",
                            LookupCode = "AR",
                            Name = "Arkansas"
                        },
                        new
                        {
                            Id = 5L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9837),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "CA",
                            LookupCode = "CA",
                            Name = "California"
                        },
                        new
                        {
                            Id = 6L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9841),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "CZ",
                            LookupCode = "CZ",
                            Name = "Canal Zone"
                        },
                        new
                        {
                            Id = 7L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9843),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "CO",
                            LookupCode = "CO",
                            Name = "Colorado"
                        },
                        new
                        {
                            Id = 8L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9845),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "CT",
                            LookupCode = "CT",
                            Name = "Connecticut"
                        },
                        new
                        {
                            Id = 9L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9847),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "DE",
                            LookupCode = "DE",
                            Name = "Delaware"
                        },
                        new
                        {
                            Id = 10L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9850),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "DC",
                            LookupCode = "DC",
                            Name = "District of Columbia"
                        },
                        new
                        {
                            Id = 11L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9852),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "FL",
                            LookupCode = "FL",
                            Name = "Florida"
                        },
                        new
                        {
                            Id = 12L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9854),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "GA",
                            LookupCode = "GA",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 13L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9856),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "GU",
                            LookupCode = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 14L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9858),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "HI",
                            LookupCode = "HI",
                            Name = "Hawaii"
                        },
                        new
                        {
                            Id = 15L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9860),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "ID",
                            LookupCode = "ID",
                            Name = "Idaho"
                        },
                        new
                        {
                            Id = 16L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9862),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "IL",
                            LookupCode = "IL",
                            Name = "Illinois"
                        },
                        new
                        {
                            Id = 17L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9864),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "IN",
                            LookupCode = "IN",
                            Name = "Indiana"
                        },
                        new
                        {
                            Id = 18L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9866),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "IA",
                            LookupCode = "IA",
                            Name = "Iowa"
                        },
                        new
                        {
                            Id = 19L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9868),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "KS",
                            LookupCode = "KS",
                            Name = "Kansas"
                        },
                        new
                        {
                            Id = 20L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9870),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "KY",
                            LookupCode = "KY",
                            Name = "Kentucky"
                        },
                        new
                        {
                            Id = 21L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9872),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "LA",
                            LookupCode = "LA",
                            Name = "Louisiana"
                        },
                        new
                        {
                            Id = 22L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9901),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "ME",
                            LookupCode = "ME",
                            Name = "Maine"
                        },
                        new
                        {
                            Id = 23L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9904),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "MD",
                            LookupCode = "MD",
                            Name = "Maryland"
                        },
                        new
                        {
                            Id = 24L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9906),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "MA",
                            LookupCode = "MA",
                            Name = "Massachusetts"
                        },
                        new
                        {
                            Id = 25L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9908),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "MI",
                            LookupCode = "MI",
                            Name = "Michigan"
                        },
                        new
                        {
                            Id = 26L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9910),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "MN",
                            LookupCode = "MN",
                            Name = "Minnesota"
                        },
                        new
                        {
                            Id = 27L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9912),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "MS",
                            LookupCode = "MS",
                            Name = "Mississippi"
                        },
                        new
                        {
                            Id = 28L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9914),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "MO",
                            LookupCode = "MO",
                            Name = "Missouri"
                        },
                        new
                        {
                            Id = 29L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9916),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "MT",
                            LookupCode = "MT",
                            Name = "Montana"
                        },
                        new
                        {
                            Id = 30L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9918),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "NE",
                            LookupCode = "NE",
                            Name = "Nebraska"
                        },
                        new
                        {
                            Id = 31L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9920),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "NV",
                            LookupCode = "NV",
                            Name = "Nevada"
                        },
                        new
                        {
                            Id = 32L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9922),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "NH",
                            LookupCode = "NH",
                            Name = "New Hampshire"
                        },
                        new
                        {
                            Id = 33L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9924),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "NJ",
                            LookupCode = "NJ",
                            Name = "New Jersey"
                        },
                        new
                        {
                            Id = 34L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9926),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "NM",
                            LookupCode = "NM",
                            Name = "New Mexico"
                        },
                        new
                        {
                            Id = 35L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9928),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "NY",
                            LookupCode = "NY",
                            Name = "New York"
                        },
                        new
                        {
                            Id = 36L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9930),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "NC",
                            LookupCode = "NC",
                            Name = "North Carolina"
                        },
                        new
                        {
                            Id = 37L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9932),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "ND",
                            LookupCode = "ND",
                            Name = "North Dakota"
                        },
                        new
                        {
                            Id = 38L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9934),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "OH",
                            LookupCode = "OH",
                            Name = "Ohio"
                        },
                        new
                        {
                            Id = 39L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9936),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "OK",
                            LookupCode = "OK",
                            Name = "Oklahoma"
                        },
                        new
                        {
                            Id = 40L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9938),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "OR",
                            LookupCode = "OR",
                            Name = "Oregon"
                        },
                        new
                        {
                            Id = 41L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9940),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "PA",
                            LookupCode = "PA",
                            Name = "Pennsylvania"
                        },
                        new
                        {
                            Id = 42L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9942),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "PR",
                            LookupCode = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 43L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9944),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "RI",
                            LookupCode = "RI",
                            Name = "Rhode Island"
                        },
                        new
                        {
                            Id = 44L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9946),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "SC",
                            LookupCode = "SC",
                            Name = "South Carolina"
                        },
                        new
                        {
                            Id = 45L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9948),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "SD",
                            LookupCode = "SD",
                            Name = "South Dakota"
                        },
                        new
                        {
                            Id = 46L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9950),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "TN",
                            LookupCode = "TN",
                            Name = "Tennessee"
                        },
                        new
                        {
                            Id = 47L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9952),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "TX",
                            LookupCode = "TX",
                            Name = "Texas"
                        },
                        new
                        {
                            Id = 48L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9954),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "UT",
                            LookupCode = "UT",
                            Name = "Utah"
                        },
                        new
                        {
                            Id = 49L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9956),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "VT",
                            LookupCode = "VT",
                            Name = "Vermont"
                        },
                        new
                        {
                            Id = 50L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9958),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "VI",
                            LookupCode = "VI",
                            Name = "Virgin Islands"
                        },
                        new
                        {
                            Id = 51L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9960),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "VA",
                            LookupCode = "VA",
                            Name = "Virginia"
                        },
                        new
                        {
                            Id = 52L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9962),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "WA",
                            LookupCode = "WA",
                            Name = "Washington"
                        },
                        new
                        {
                            Id = 53L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9964),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "WV",
                            LookupCode = "WV",
                            Name = "West Virginia"
                        },
                        new
                        {
                            Id = 54L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9966),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "WI",
                            LookupCode = "WI",
                            Name = "Wisconsin"
                        },
                        new
                        {
                            Id = 55L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9968),
                            Deleted = false,
                            Description = "",
                            DictionaryListId = 1L,
                            ExternalId = "WY",
                            LookupCode = "WY",
                            Name = "Wyoming"
                        },
                        new
                        {
                            Id = 56L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9970),
                            Deleted = false,
                            Description = "Milligram",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "mg",
                            Name = "Milligram"
                        },
                        new
                        {
                            Id = 57L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9972),
                            Deleted = false,
                            Description = "Gram",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "g",
                            Name = "Gram"
                        },
                        new
                        {
                            Id = 58L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9974),
                            Deleted = false,
                            Description = "Kilogram",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "kg",
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 59L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9976),
                            Deleted = false,
                            Description = "Ounce",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "oz",
                            Name = "Ounce"
                        },
                        new
                        {
                            Id = 60L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9978),
                            Deleted = false,
                            Description = "Pound",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "lb",
                            Name = "Pound"
                        },
                        new
                        {
                            Id = 61L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9980),
                            Deleted = false,
                            Description = "Ton",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "ton",
                            Name = "Ton"
                        },
                        new
                        {
                            Id = 62L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9982),
                            Deleted = false,
                            Description = "Cup",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "cup",
                            Name = "Cup"
                        },
                        new
                        {
                            Id = 63L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9984),
                            Deleted = false,
                            Description = "Table Spoon",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "ts",
                            Name = "Table Spoon"
                        },
                        new
                        {
                            Id = 64L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 587, DateTimeKind.Local).AddTicks(9986),
                            Deleted = false,
                            Description = "Unit",
                            DictionaryListId = 2L,
                            ExternalId = "",
                            LookupCode = "unit",
                            Name = "Unit"
                        },
                        new
                        {
                            Id = 65L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 588, DateTimeKind.Local).AddTicks(12),
                            Deleted = false,
                            Description = "Vegetable",
                            DictionaryListId = 3L,
                            ExternalId = "",
                            LookupCode = "VEG",
                            Name = "Vegetable"
                        },
                        new
                        {
                            Id = 66L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 588, DateTimeKind.Local).AddTicks(15),
                            Deleted = false,
                            Description = "Meat",
                            DictionaryListId = 3L,
                            ExternalId = "",
                            LookupCode = "MEAT",
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 67L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 588, DateTimeKind.Local).AddTicks(17),
                            Deleted = false,
                            Description = "Herb",
                            DictionaryListId = 3L,
                            ExternalId = "",
                            LookupCode = "HERB",
                            Name = "Herb"
                        },
                        new
                        {
                            Id = 68L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 588, DateTimeKind.Local).AddTicks(19),
                            Deleted = false,
                            Description = "Fruit",
                            DictionaryListId = 3L,
                            ExternalId = "",
                            LookupCode = "FRUIT",
                            Name = "Fruit"
                        },
                        new
                        {
                            Id = 69L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 588, DateTimeKind.Local).AddTicks(21),
                            Deleted = false,
                            Description = "Grain",
                            DictionaryListId = 3L,
                            ExternalId = "",
                            LookupCode = "GRAIN",
                            Name = "Grain"
                        },
                        new
                        {
                            Id = 70L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 588, DateTimeKind.Local).AddTicks(23),
                            Deleted = false,
                            Description = "Spice",
                            DictionaryListId = 3L,
                            ExternalId = "",
                            LookupCode = "SPICE",
                            Name = "Spice"
                        },
                        new
                        {
                            Id = 71L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 588, DateTimeKind.Local).AddTicks(25),
                            Deleted = false,
                            Description = "Restaurant",
                            DictionaryListId = 4L,
                            ExternalId = "",
                            LookupCode = "RESTAURANT",
                            Name = "Restaurant"
                        },
                        new
                        {
                            Id = 72L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 588, DateTimeKind.Local).AddTicks(27),
                            Deleted = false,
                            Description = "Supplier",
                            DictionaryListId = 4L,
                            ExternalId = "",
                            LookupCode = "SUPPLIER",
                            Name = "Supplier"
                        },
                        new
                        {
                            Id = 73L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 588, DateTimeKind.Local).AddTicks(29),
                            Deleted = false,
                            Description = "Corporate",
                            DictionaryListId = 4L,
                            ExternalId = "",
                            LookupCode = "CORPORATE",
                            Name = "Corporate"
                        },
                        new
                        {
                            Id = 74L,
                            Active = true,
                            Creator = 9999,
                            DateCreated = new DateTime(2024, 7, 13, 16, 41, 6, 588, DateTimeKind.Local).AddTicks(31),
                            Deleted = false,
                            Description = "Reseller",
                            DictionaryListId = 4L,
                            ExternalId = "",
                            LookupCode = "RESELLER",
                            Name = "Reseller"
                        });
                });

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.CRM.BusinessEntity", b =>
                {
                    b.HasOne("CulinaryAnalytics.Models.Entities.Common.DictionaryListItem", "BusinessEntityType")
                        .WithMany("BusinessEntities")
                        .HasForeignKey("BusinessEntityTypeId");

                    b.Navigation("BusinessEntityType");
                });

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.CRM.Location", b =>
                {
                    b.HasOne("CulinaryAnalytics.Models.Entities.CRM.BusinessEntity", "Business")
                        .WithMany("Locations")
                        .HasForeignKey("BusinessEntityId");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.CRM.Person", b =>
                {
                    b.HasOne("CulinaryAnalytics.Models.Entities.CRM.Location", "Location")
                        .WithMany("People")
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.Common.DictionaryListItem", b =>
                {
                    b.HasOne("CulinaryAnalytics.Models.Entities.Common.DictionaryList", "Dictionary")
                        .WithMany("Items")
                        .HasForeignKey("DictionaryListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");
                });

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.CRM.BusinessEntity", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.CRM.Location", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.Common.DictionaryList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CulinaryAnalytics.Models.Entities.Common.DictionaryListItem", b =>
                {
                    b.Navigation("BusinessEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
